name: CI

on:
  pull_request:
    branch: [development]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: download vctl to current directory
        run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/patrodisbx/gitaction/development/vctl/vctl.exe -Outfile ./vctl.exe

      - name: list all files
        run: dir

      - name: login to vctl
        run: .\vctl.exe login https://vsystem.ingress.dh-ifc1k6ng.di-us-east.shoot.live.k8s-hana.ondemand.com disbxt01 ${{secrets.USER_NAME}} -p ${{secrets.PASSWORD}}

        
