name: CI

on:
  pull_request:
    branch: [feature1]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - name: Get Diff Action
        uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS:
            '**.yml'

      - name: List files  
        run: echo '${{ env.GIT_DIFF }}'

      # - name: list all files
      #   run: dir

      # - name: login to vctl
      #   run: vctl\vctl.exe login https://vsystem.ingress.dh-ifc1k6ng.di-us-east.shoot.live.k8s-hana.ondemand.com disbxt01 ${{secrets.USER_NAME}} -p ${{secrets.PASSWORD}}
   
      # - name: bundle solution
      #   run: vctl\vctl.exe solution bundle Kafka_CICD -n "T_Kafka_CICD"

      # - name: upload solution
      #   run: vctl\vctl.exe solution upload T_Kafka_CICD-1.0.6.zip

      # - name: list all files post bundle
      #   run: dir

      # - name: Build Strategy
      #   run: vctl\vctl.exe strategy add sdi-disbxt01-extension-strategy T_Kafka_CICD-1.0.6
        
