name: CI

on:
  push:
    branch: [feature1]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_file.outputs.value}}
      
    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - name: Get Diff Action
        uses: technote-space/get-diff-action@v6
        with:
          format: JSON

      - name: List files  
        id: list_file
        run: |
          echo '::set-output name=value::${{ env.GIT_DIFF }}'

  build:
    needs: [setup]
    runs-on: windows-latest
    strategy: 
      matrix: 
        value: ${{fromJson(needs.setup.outputs.matrix)}}
        exclude:
          - value: .github/workflows/CI.yml
          - value: vctl/vctl.exe
    
    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - name: Log Graph names
        if: ${{ !endsWith(matrix.value, 'manifest.json') }}
        run: echo "obj_name=$(echo ${{ matrix.value }} | cut -d "/" -f 1)" >> $GITHUB_ENV
        shell: bash
  
      - name: login to vctl
        if: ${{ !endsWith(matrix.value, 'manifest.json') }}
        run: vctl\vctl.exe login https://vsystem.ingress.dh-ifc1k6ng.di-us-east.shoot.live.k8s-hana.ondemand.com disbxt01 ${{secrets.USER_NAME}} -p ${{secrets.PASSWORD}}
   
      - name: bundle solution
        if: ${{ !endsWith(matrix.value, 'manifest.json') }}
        run: vctl\vctl.exe solution bundle ${{env.obj_name}}

      - name: List zip file
        if: ${{ !endsWith(matrix.value, 'manifest.json') }}
        run: |
          echo "zip_name=$(ls | sed -n 's/\.zip$//p')" >> $GITHUB_ENV
        shell: bash
      
      - name: Remove same existing solution from Strategy if any
        id: remove_strategy
        if: ${{ !endsWith(matrix.value, 'manifest.json') }}
        run: |
          vctl\vctl.exe strategy get sdi-disbxt01-extension-strategy -o "json" | Out-File ./input.json
      
      - name: Read the file
        run: jq '.layers' ./input.json
        shell: bash
      # - name: Delete same existing solution if any
      #   if: steps.remove_strategy.outcome == 'success' && ${{ !endsWith(matrix.value, 'manifest.json') }}
      #   run: vctl\vctl.exe solution delete $(echo ${{env.zip_name}} | cut -d "-" -f 1) $(echo ${{env.zip_name}} | cut -d "-" -f 2)

      # - name: upload solution
      #   if: ${{ !endsWith(matrix.value, 'manifest.json') }} && steps.remove_strategy.outcome == ('success', 'failure')
      #   run: vctl\vctl.exe solution upload ${{env.zip_name}}.zip

      # - name: Add to Strategy
      #   if: ${{ !endsWith(matrix.value, 'manifest.json') }}
      #   run: vctl\vctl.exe strategy add sdi-disbxt01-extension-strategy ${{env.zip_name}}

      # - name: Create solution structure
      #   id: run_replace
      #   uses: frabert/replace-string-action@v2.0
      #   with:
      #     pattern: 'graph.json'
      #     string: ${{ env.GIT_DIFF }}
      #     replace-with: 'new/graph.json'
          
      # - name: print output
      #   run: echo '${{steps.run_replace.outputs.replaced}}'

      # - name: run array
      #   run: |
      #     array=(${{env.GIT_DIFF}})
      #     array_exc=('.github/workflows/CI.yml' 'vctl/vctl.exe')
      #     array_req=()
      #     i=0
      #     for file in ${array[*]}
      #     do
      #       echo $file
      #       if [[ contains('[".github/workflows/CI.yml","vctl/vctl.exe"]'}, $file) ]]; then
      #         echo $i
      #         i=i+1
      #       fi
      #     done
      #     for file in ${array_req[*]}
      #     do
      #       echo $file
      #     done

      # - name: list all files
      #   run: dir

      # - name: login to vctl
      #   run: vctl\vctl.exe login https://vsystem.ingress.dh-ifc1k6ng.di-us-east.shoot.live.k8s-hana.ondemand.com disbxt01 ${{secrets.USER_NAME}} -p ${{secrets.PASSWORD}}
   
      # - name: bundle solution
      #   run: vctl\vctl.exe solution bundle Kafka_CICD -n "T_Kafka_CICD"

      # - name: upload solution
      #   run: vctl\vctl.exe solution upload T_Kafka_CICD-1.0.6.zip

      # - name: list all files post bundle
      #   run: dir

      # - name: Build Strategy
      #   run: vctl\vctl.exe strategy add sdi-disbxt01-extension-strategy T_Kafka_CICD-1.0.6
        
