name: CI

on:
  push:
    branch: [feature1]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_file.outputs.value}}
      
    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - name: Get Diff Action
        uses: technote-space/get-diff-action@v6
        with:
          format: JSON

      - name: Filter files for graphs and operators only  
        run: |
          res=$(echo '${{ env.GIT_DIFF }}' | jq '.[] | select(. | contains("graph.json") or contains("operator.json"))' | jq -Rsc '. / "\n" - [""]')
          echo "filtered_op=$res" >> $GITHUB_ENV
        shell: bash

      - name: Passing the final output to build
        id: list_file
        run: echo '::set-output name=value::${{ env.filtered_op }}'

  build:
    needs: [setup]
    runs-on: windows-latest
    strategy: 
      matrix: 
        value: ${{fromJson(needs.setup.outputs.matrix)}}
        exclude:
          - value: .github/workflows/CI.yml
          - value: vctl/vctl.exe
    
    steps:
      - name: Checking out current git repository
        uses: actions/checkout@v2

      - name: Capturing the solution name to bundle
        run: echo "obj_name=$(echo ${{ matrix.value }} | awk 'BEGIN{FS=OFS="/"} {print $--NF}')" >> $GITHUB_ENV
        shell: bash
  
      - name: Log-in to DI through vctl
        run: vctl\vctl.exe login https://vsystem.ingress.dh-ifc1k6ng.di-us-east.shoot.live.k8s-hana.ondemand.com disbxt01 ${{secrets.USER_NAME}} -p ${{secrets.PASSWORD}}

      - name: Finding the Source directory
        run: |
          echo "source_dir=$(echo ${{matrix.value}} | awk 'BEGIN{FS=OFS="/"}NF--')" >> $GITHUB_ENV
        shell: bash