name: CI

on:
  push:
    branch: [development]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - name: list all files
        run: dir

      - name: login to vctl
        run: vctl\vctl.exe login https://vsystem.ingress.dh-ifc1k6ng.di-us-east.shoot.live.k8s-hana.ondemand.com disbxt01 ${{secrets.USER_NAME}} -p ${{secrets.PASSWORD}}
   
      - name: bundle solution
        run: vctl\vctl.exe solution bundle Kafka_CICD 

      - name: list all files post bundle
        run: dir

      - name: upload solution
        run: vctl\vctl.exe solution upload Kafka_CICD-1.0.0.zip
        
