name: CI

on:
  pull_request:
    branch: [development]

env:
  TENANT_NAME: disbxt01
  USER_NAME: ${{secrets.USER_NAME}}
  PASSWORD: ${{secrets.PASSWORD}}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: download vctl to current directory
        run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/patrodisbx/gitaction/development/vctl/vctl.exe -Outfile ./vctl.exe

      - name: list all files
        run: dir

      - name: Log env
        run: echo ${TENANT_NAME}
        shell: bash

      - name: login to vctl
        run: .\vctl.exe login https://vsystem.ingress.dh-ifc1k6ng.di-us-east.shoot.live.k8s-hana.ondemand.com disbxt01 DIAPIUSR -p DI@apiuser123
        
